### PR TITLE
Update chains.json

### PR DESCRIPTION
**Pull request by jihuiling**
https://bscscan.com/tx/0xb2731df366db70bab4cc03b729c925924d2a284878c429c09f0604bef2968516

### CODE REVIEW

**Comment by opera0001** [comment]
image

Please submit according to this pixel.

**Comment by jihuiling** [comment]
图片颜色和尺寸更新好了

**Comment by opera0001** [comment]
Remember to complete the hash value.

https://bscscan.com/tx/0xef242444be1fe8a65ae424b2bb2da2758b96aa0be6405e000c8071b6302d97f5

**Comment by jihuiling** [comment]
https://bscscan.com/tx/0xef242444be1fe8a65ae424b2bb2da2758b96aa0be6405e000c8071b6302d97f5

**Comment by jihuiling** [comment]
completed

**Comment by opera0001** [comment]
Using IPFS may impact the display of images in the wallet. Are you sure about proceeding with this?

**Pull request merged**
