### PR TITLE
add vision mainnet and testnet

### PR DESCRIPTION
**Pull request by vchain007**
add vision network .but we wonder how to add my 88px png to https://tp-upload.cdn.bcebos.com/v1/blockChain/vision/select-88px.png , can u give some entrance to upload

More detail:
https://www.v.network
https://github.com/vision-consensus
https://www.visionscan.org
https://github.com/ethereum-lists/chains/blob/master/_data/chains/eip155-666666.json
https://github.com/ethereum-lists/chains/blob/master/_data/chains/eip155-888888.json

### CODE REVIEW

**Comment by vchain007** [comment]
select-88px
unselect-88px

**Comment by chendatony31** [comment]
The URL in `app_resource` can not be reached  @vchain007

**Comment by vchain007** [comment]
88px png resource have attached to this pr .
we wonder how to add my 88px png to https://tp-upload.cdn.bcebos.com/v1/blockChain/vision/select-88px.png , can u give some entrance to upload

**Comment by chendatony31** [comment]
`https://tp-upload.cdn.bcebos.com/v1/blockChain/vision/select-88px.png` is just a demo, you should upload images into your own server, and provide a URL that can be visited public.

**Comment by vchain007** [comment]
already update app_resource
plz review again

**Pull request merged**
