### PR TITLE
Update chains.json

### PR DESCRIPTION
**Pull request by wangxihaowxh**

### CODE REVIEW

**Comment by opera0001** [comment]
The TokenPocket wallet development team has been working to provide more potential chains to the community of developers and wallet users, and to provide a more friendly way to support new public chains.

Combined with the feedback from the community users and developers for a long time, we decided to expand the original two ways of supporting new chains into three: 1. convenient addition of chains 2. support of simple public chains 3. support of complete public chains to promote the docking, inclusion and rapid use of public chains through segmentation, so we specially send you a message to check the content of our new requirements for new public chains:.
EN：https://help.tokenpocket.pro/developer-en/network/add-chain  
CN：https://help.tokenpocket.pro/developer-cn/public-chain/add-chain  

You can check the relevant rules and submit information according to your actual needs. Thank you again for your support and recognition of TokenPocket.

**Comment by wangxihaowxh** [comment]
您好，我们需要高级支持。 但是 我提交的这个PR，里面没有交易详情和列表接口， 之前问过贵房，回答是： 附加的，先不用填。

**Comment by wangxihaowxh** [comment]
我们现在捐赠1千万的TPT， 之后交易详情和列表接口，如何提交给你们呢

**Comment by opera0001** [comment]
We have received your feedback and hope that you can provide more data. We will discuss your project. If it finally passes the review, then we can support your project, so don't worry about donating so far. thank you very much.

**Comment by wangxihaowxh** [comment]
好的，也非常感谢你们。   本次提交是一些基础信息，包含了，浏览器链接，链ID， RPC链接。  现在没有交易记录详情和列表， 我之后要将这些放在哪个字段里面合适呢？

**Comment by wangxihaowxh** [comment]
噢噢，我现在看到了，交易详情和logo放在这里：  "txUrl":" https://xxxchaintxserver.xxx.xxx"

**Comment by wangxihaowxh** [comment]
txUrl信息我已经添加了， 在最新的提交里面。 麻烦审核通过一下。 审核通过后希望通过捐赠在钱包中列出来。

**Comment by wangxihaowxh** [comment]
> We have received your feedback and hope that you can provide more data. We will discuss your project. If it finally passes the review, then we can support your project, so don't worry about donating so far. thank you very much.

您好，交易详情接口URL信息已经提交了，烦请核实， 有何不正确的地方还请回复一下。通过后希望能在TP上列出公链，我们准备好捐赠的1千万TPT。

**Pull request closed without merging**
