### PR TITLE
add Kon Mainnet

### PR DESCRIPTION
**Pull request by benjioh5**
:)

### CODE REVIEW

**Comment by opera0001** [comment]
Please fill in the chains.json content as required by the official instructions. Your submission is incomplete; please double-check.

**Comment by opera0001** [comment]
image

**Comment by benjioh5** [comment]
@opera0001

**Comment by opera0001** [comment]
image

Please pay attention to the pixel size when submitting the icon.

**Comment by benjioh5** [comment]
updated. @opera0001

**Comment by opera0001** [comment]
The submitted content is complete. Please provide the donation hash link. Thank you.

**Comment by Jessiejaymz810s** [comment]
dapp@tokenpocket.pro

**Comment by opera0001** [comment]
> [dapp@tokenpocket.pro](mailto:dapp@tokenpocket.pro)

Did not understand the meaning of your expression.

**Pull request closed without merging**
