### PR TITLE
Update chains.json

### PR DESCRIPTION
**Pull request by PcdDao**
Add Phecda Chain info
donation hex   https://bscscan.com/tx/0xb33e06fd09bf5f8801d99ec9a2d2e79a28fe78fe34bc7639493592d701a4bfc1

### CODE REVIEW

**Comment by opera0001** [comment]
image
image

Dear, the JSON data you submitted seems to have some issues, making it impossible to merge in this state. Please delete the JSON and re-add it, or close the order and try creating a new one.

**Comment by xc-link** [comment]
Add Phecda Chain info

**Comment by xc-link** [comment]
git status

**Comment by xc-link** [comment]
git add

**Comment by xc-link** [comment]
git commit

**Comment by opera0001** [comment]
Dear, there is no issue with the donation, but the JSON content submitted is not formatted correctly, so it cannot be merged. You need to modify the JSON content accordingly.
image

**Comment by opera0001** [comment]
I'm unable to provide my Telegram contact information. However, feel free to share any specific issues you have here, and I will do my best to help you resolve them quickly.

**Pull request closed without merging**
